version: '3'

services:
  master:
    build: .
    image: danguderian/spark_image:validation
    container_name: master
    ports:
      - 4040:4040
      - 7077:7077
      - 8080:8080
      - 6066:6066
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]
 
  slave:
    image: danguderian/spark_image:validation
    depends_on:
      - master
    ports:
      - "8081"
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]
    volumes:
        - ./docker-volume/spark-output/:/opt/output

  history-server:
      image: danguderian/spark_image:validation
      container_name: history-server
      depends_on:
        - master
      ports:
        - "18080:18080"
      command: ["/usr/bin/supervisord", "--configuration=/opt/conf/history-server.conf"]
      volumes:
        - ./docker-volume/spark-output/:/opt/output
